<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Delete\" />
      <Folder Include="Edit\" />
      <Folder Include="GetRecipeById\" />
      <Folder Include="GetRecipesByUserId\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Entities\Entities.csproj" />
    </ItemGroup>

</Project>
