FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["InteractionService/Host/Host.csproj", "InteractionService/Host/"]
COPY ["InteractionService/Infrastructure/Infrastructure.csproj", "InteractionService/Infrastructure/"]
COPY ["InteractionService/Entities/Entities.csproj", "InteractionService/Entities/"]
COPY ["InteractionService/UseCases/UseCases.csproj", "InteractionService/UseCases/"]
COPY ["InteractionService/Presentation/Presentation.csproj", "InteractionService/Presentation/"]
RUN dotnet restore "InteractionService/Host/Host.csproj"
COPY . .
WORKDIR "/src/InteractionService/Host"
RUN dotnet build "./Host.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Host.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Host.dll"]
